export const dataSource = [
        {
            key: '1',
            goods_name: '麦车饰 车载手机支架 仪表台多功能汽车用磁性手机座创意金属导航支架 通用车载收纳 汽车用品 手机饮料架 CXZJ-0',
            goods_price: 39,
            goods_number: '100',
            goods_weight: '100',
            goods_state:'0',
            add_time:'1578298271',
            hot_mumber:'0',
            is_promote:'false',

      },
      {
            key: '2',
            goods_name: '麦车饰 车载手机支架 仪表台多功能汽车用磁性手机座创意金属导航支架 通用车载收纳 汽车用品 手机饮料架 CXZJ-0',
            goods_price: 39,
            goods_number: '100',
            goods_weight: '100',
            goods_state:'0',
            add_time:'1578298271',
            hot_mumber:'0',
            is_promote:'false',
      },
      {
            key: '3',
            goods_name: '麦车饰 车载手机支架 仪表台多功能汽车用磁性手机座创意金属导航支架 通用车载收纳 汽车用品 手机饮料架 CXZJ-0',
            goods_price: 39,
            goods_number: '100',
            goods_weight: '100',
            goods_state:'0',
            add_time:'1578298271',
            hot_mumber:'0',
            is_promote:'false',
      },
      {
            key: '4',
            goods_name: '麦车饰 车载手机支架 仪表台多功能汽车用磁性手机座创意金属导航支架 通用车载收纳 汽车用品 手机饮料架 CXZJ-0',
            goods_price: 39,
            goods_number: '100',
            goods_weight: '100',
            goods_state:'0',
            add_time:'1578298271',
            hot_mumber:'0',
            is_promote:'false',
      },
]